#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Mar 08 10:48:43 MST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ff26aa95400749cb8e566d417f7382ad --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot stopwatch_top_behav xil_defaultlib.stopwatch_top xil_defaultlib.glbl -log elaborate.log"
xelab -wto ff26aa95400749cb8e566d417f7382ad --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot stopwatch_top_behav xil_defaultlib.stopwatch_top xil_defaultlib.glbl -log elaborate.log

