#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Apr 11 16:59:38 MDT 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a58b303b8c7446f6bf13c545a2f5c01c --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot VLineDrawer_behav xil_defaultlib.VLineDrawer xil_defaultlib.glbl -log elaborate.log"
xelab -wto a58b303b8c7446f6bf13c545a2f5c01c --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot VLineDrawer_behav xil_defaultlib.VLineDrawer xil_defaultlib.glbl -log elaborate.log

