webtalk_init -webtalk_dir /auto/fsi/nrbenn14/ECEn_220/labs/12lab_good/12lab_good.sim/sim_1/behav/xsim/xsim.dir/top_pong_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 11 17:32:11 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211999856_1777556260_210756658_920" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8f105451-81ef-4ee7-914d-8665cc1b9043" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c8ac1f9239484dc78a1296b6f97893bb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3694.228 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "101 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "59.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126068_KB" -context "xsim\\usage"
webtalk_transmit -clientid 449238099 -regid "211999856_1777556260_210756658_920" -xml /auto/fsi/nrbenn14/ECEn_220/labs/12lab_good/12lab_good.sim/sim_1/behav/xsim/xsim.dir/top_pong_behav/webtalk/usage_statistics_ext_xsim.xml -html /auto/fsi/nrbenn14/ECEn_220/labs/12lab_good/12lab_good.sim/sim_1/behav/xsim/xsim.dir/top_pong_behav/webtalk/usage_statistics_ext_xsim.html -wdm /auto/fsi/nrbenn14/ECEn_220/labs/12lab_good/12lab_good.sim/sim_1/behav/xsim/xsim.dir/top_pong_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
