#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Mar 22 10:10:50 MDT 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 0505105cb675457b8cdc740265750e91 --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot codebreaker_serial_top_behav xil_defaultlib.codebreaker_serial_top xil_defaultlib.glbl -log elaborate.log"
xelab -wto 0505105cb675457b8cdc740265750e91 --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot codebreaker_serial_top_behav xil_defaultlib.codebreaker_serial_top xil_defaultlib.glbl -log elaborate.log

